language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
#  - pip install unittest
# command to run tests
script:
  - unittest